# Generated by Django 3.2.7 on 2021-11-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_comment_conversation_foro_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='author',
        ),
        migrations.RemoveField(
            model_name='foro',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='team_pg',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Foro',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Team_pg',
        ),
    ]
